# Form implementation generated from reading ui file '/Users/gdlocal/Desktop/myCode/monitoring_fail/ui/FilterConfigInfo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 400)
        Form.setMaximumSize(QtCore.QSize(400, 400))
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 401, 391))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 0, 60, 16))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 391, 221))
        self.listWidget.setObjectName("listWidget")
        self.label_shielding_test_name = QtWidgets.QLabel(parent=self.groupBox)
        self.label_shielding_test_name.setGeometry(QtCore.QRect(0, 240, 81, 21))
        self.label_shielding_test_name.setObjectName("label_shielding_test_name")
        self.textEdit_shielding_test_name = QtWidgets.QTextEdit(parent=self.groupBox)
        self.textEdit_shielding_test_name.setGeometry(QtCore.QRect(0, 260, 391, 51))
        self.textEdit_shielding_test_name.setObjectName("textEdit_shielding_test_name")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 320, 201, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_start = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_start.setObjectName("label_start")
        self.verticalLayout_2.addWidget(self.label_start)
        self.label_end = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_end.setObjectName("label_end")
        self.verticalLayout_2.addWidget(self.label_end)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(parent=self.layoutWidget)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.verticalLayout.addWidget(self.dateTimeEdit_start)
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(parent=self.layoutWidget)
        self.dateTimeEdit_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2100, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.verticalLayout.addWidget(self.dateTimeEdit_end)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 320, 161, 60))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_save = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_3.addWidget(self.pushButton_save)
        self.pushButton_reset = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_3.addWidget(self.pushButton_reset)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "slot_ID"))
        self.label_shielding_test_name.setText(_translate("Form", "屏蔽测试项目"))
        self.textEdit_shielding_test_name.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Verdana\',\'Arial\'; font-size:10px; color:#000000;\">Atlas_Group_CHECK_STATION_SECURITY;Atlas_Group_OrphanedRequiredLimits;Atlas_Group_OrphanedRecords</span></p></body></html>"))
        self.label_start.setText(_translate("Form", "开始时间"))
        self.label_end.setText(_translate("Form", "结束时间"))
        self.pushButton_save.setText(_translate("Form", "save"))
        self.pushButton_reset.setText(_translate("Form", "reset"))
