# Form implementation generated from reading ui file '/Users/gdlocal/Desktop/myCode/py3/pyqtgraph_/only_fail/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ui_test(object):
    def setupUi(self, ui_test):
        ui_test.setObjectName("ui_test")
        ui_test.resize(1038, 859)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ui_test.sizePolicy().hasHeightForWidth())
        ui_test.setSizePolicy(sizePolicy)
        ui_test.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ui_test)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_config = QtWidgets.QGroupBox(parent=ui_test)
        self.groupBox_config.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_config.setObjectName("groupBox_config")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_config)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.groupBox_config)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout.addWidget(self.pushButton_clear)
        self.label_time = QtWidgets.QLabel(parent=self.groupBox_config)
        self.label_time.setStyleSheet("QLabel {\n"
"                font-size: 14px;\n"
"                color: #333333;\n"
"                background-color: #f5f5f5;\n"
"                padding: 10px 16px;\n"
"                border-radius: 6px;\n"
"                border: 1px solid #e0e0e0;\n"
"                min-width:140px;  \n"
"                text-align: center;  \n"
"            }")
        self.label_time.setWordWrap(True)
        self.label_time.setObjectName("label_time")
        self.verticalLayout.addWidget(self.label_time)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox_config)
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_slotid_name = QtWidgets.QPushButton(parent=self.groupBox_config)
        self.pushButton_slotid_name.setObjectName("pushButton_slotid_name")
        self.horizontalLayout_2.addWidget(self.pushButton_slotid_name)
        self.lineEdit_slotid_name = QtWidgets.QLineEdit(parent=self.groupBox_config)
        self.lineEdit_slotid_name.setObjectName("lineEdit_slotid_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_slotid_name)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit_logpath = QtWidgets.QTextEdit(parent=self.groupBox_config)
        self.textEdit_logpath.setObjectName("textEdit_logpath")
        self.verticalLayout_4.addWidget(self.textEdit_logpath)
        self.pushButton_get_failcsv = QtWidgets.QPushButton(parent=self.groupBox_config)
        self.pushButton_get_failcsv.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_get_failcsv.setObjectName("pushButton_get_failcsv")
        self.verticalLayout_4.addWidget(self.pushButton_get_failcsv)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_config)
        self.groupBox = QtWidgets.QGroupBox(parent=ui_test)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_fail = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidget_fail.setObjectName("tableWidget_fail")
        self.tableWidget_fail.setColumnCount(0)
        self.tableWidget_fail.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_fail)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(ui_test)
        QtCore.QMetaObject.connectSlotsByName(ui_test)

    def retranslateUi(self, ui_test):
        _translate = QtCore.QCoreApplication.translate
        ui_test.setWindowTitle(_translate("ui_test", "Version:0.1_by:zjx"))
        self.groupBox_config.setTitle(_translate("ui_test", "config"))
        self.pushButton_clear.setText(_translate("ui_test", "清除数据"))
        self.label_time.setText(_translate("ui_test", "<html><head/><body><p>2024-11-11 11:11:11</p><p>2024-11-11 11:11:11</p></body></html>"))
        self.pushButton_slotid_name.setText(_translate("ui_test", "通道号-测试项名称修改"))
        self.pushButton_get_failcsv.setText(_translate("ui_test", "提取fail信息-拖动log到上方输入框，按下该按钮"))
        self.groupBox.setTitle(_translate("ui_test", "FAIL"))
